### ISSUE TITLE
[REQ] license fix on GH

### ISSUE THREAD

**Issue by forart** [acoustid/chromaprint#109]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Fingerprinting section](https://github.com/forart/HyMPS/blob/main/Fingerprinting.md)), can you please set correct licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/acoustid/chromaprint?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/acoustid/chromaprint/?label=LICENSE)

...maybe it's a GH setup issue ?

Thanks in advance.

**Comment by lalinsky** [comment]
It probably doesn't work, because the license for the project as whole is not as straight forward. Most of code is MIT licensed, but it includes some LGPL code, which effectively makes the entire built library LGPL.
