### ISSUE TITLE
API key not working

### ISSUE THREAD

**Issue by lucas42** [acoustid/chromaprint#11]
Accessing the API using the key shown on http://acoustid.org/api-key returns an error {"status": "error", "error": {"message": "invalid API key", "code": 4}}
Using the example API key shown in the documentation works fine.

I've tried generating a new key, but that didn't work either.

**Comment by loretoparisi** [comment]
@lalinsky just to be clear:

```
acoustid("./data/B00IMFOVEG.mp3",
	{
		key: "yyyyy",
		meta: {
			client: "xxxxx"
		}, 
		fpcalc: {
			command: './bin/darwin/fpcalc'
		}
	}, function (err, results) {
		if (err) throw err;
		console.log(results);
	});
```

In my case this works for me with or without the `meta`. Also I don't see any `user` key.
