### ISSUE TITLE
ffmpeg 

### ISSUE THREAD

**Issue by BahaaeddineTJH** [acoustid/chromaprint#111]
I have a problem when I try to download chromaprint I have this error can someone help me ?
I have already downloaded ffmpeg but I still don't know why I have this error 

![image](https://user-images.githubusercontent.com/55889015/153776251-9671f198-f841-4dc6-8be6-05a788062c31.png)

**Comment by jonaski** [comment]
You can add `-DFFMPEG_ROOT` to cmake to point to ffmpeg, for example.: `-DFFMPEG_ROOT=/usr`
