### ISSUE TITLE
No linuxarm64 binary

### ISSUE THREAD

**Issue by springjools** [acoustid/chromaprint#113]
I cannot find a binary for linux arm64

**Comment by rednoah** [comment]
If you're using a popular distribution, then you can probably just use the package manager to install the `chromaprint-tools` package:
https://packages.debian.org/bookworm/libchromaprint-tools

**Comment by Sheraff** [comment]
The issue is that libchromaprint-tools is about 250Mo, when fpcalc is just 1% of that... I'd love to be able to just get an arm64 fpcalc.

**Comment by lalinsky** [comment]
Will try to get this done. I'm never sure which ARM variants are there, as arm64 is a very general specification.

**Comment by lalinsky** [comment]
Can you test the binaries from here? https://github.com/acoustid/chromaprint/actions/runs/3397137863

**Comment by Sheraff** [comment]
Thanks @lalinsky! It is very cool that you did that!

This worked for me on "Raspbian" (raspberry pi Debian). Though I had installed the full libchromaprint-tools on it before and I didn't remove that for the test. So I can attest that the chromaprint-linux-arm64 binary works on my OS, but not that it is fully self-contained.
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I'm willing to do other tests if you need me to, but I'll have to be a little more guided. My linux skills aren't strong and I'm doing it all headless through ssh.
