### ISSUE TITLE
Do fingerprints cut off the last note? 

### ISSUE THREAD

**Issue by Cortexelus** [acoustid/chromaprint#124]
Looking at the [fingerprint configuration](https://github.com/acoustid/chromaprint/blob/516e3b31c7fa6e822035ea3b3e31f9c7f51ef4b6/src/fingerprinter_configuration.cpp)
<img width="688" alt="image" src="https://user-images.githubusercontent.com/2453861/204076227-ab548bef-ed9c-4fa0-96c9-a730e6b74105.png">

If I understand the definition of filter correctly, `Filter(type, y, h, w)` defined [here](https://github.com/acoustid/chromaprint/blob/516e3b31c7fa6e822035ea3b3e31f9c7f51ef4b6/src/filter.h#L14)

For all of these filters, `y+h <= 11` 
but there's **12** chroma features
meaning none of these filters touch the 12th feature? _(the note A or Ab maybe?)_

**Comment by lalinsky** [comment]
Yes, I've noticed this a long time ago, one column of the spectral image window is completely ignored.
