### ISSUE TITLE
Can't install, FFmpeg not found

### ISSUE THREAD

**Issue by NabilEL** [acoustid/chromaprint#26]
Hi, 
I'm trying to install chromaprint on Ubuntu 16.04 but CMake keeps telling me that FFmpeg can't be found. 
I'm certain ffmpeg is installed and`which ffmpeg` returns `/usr/local/bin/ffmpeg`

Any solution ?
Thanks.

**Comment by sampsyo** [comment]
Please include a full report: what command did you run exactly, and what was the exact output?

**Comment by sampsyo** [comment]
Oops! I misread the source on this report and thought it was on the one I maintain (the Python bindings). Sorry for commenting too quickly—although I'm sure @lalinsky would appreciate more detail too.

**Comment by NabilEL** [comment]
Yeah, my bad.

Command : `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON .` 

Result : 

> FFTW3 lib not found. Set FFTW3_DIR to find it.
> 
> -- Could NOT find KissFFT (missing:  KISSFFT_SOURCE_DIR) 
> CMake Error at CMakeLists.txt:123 (message):
> 
>   Neither FFmpeg with avfft.h nor FFTW3 found
> -- Configuring incomplete, errors occurred!

**Comment by lalinsky** [comment]
You need the FFmpeg libraries, not the command line tool. I suggest you use FFmpeg from Ubuntu reporitoes:

    apt install libavcodec-dev libavformat-dev libavutil-dev

After installing those packages, it should work.

Also, unless you have an specific reason to compile the library, you could also install Chromaprint from the repository. The package `libchromaprint-tools` will give you the `fpcalc` tool and `libchromaprint-dev` will give you the development library.

**Comment by NabilEL** [comment]
Thanks, that fixed it.
