### ISSUE TITLE
fpcalc ignore errors

### ISSUE THREAD

**Issue by elliotd123** [acoustid/chromaprint#32]
I found that fpcalc exits in an error status if there's problems in the stream. In my case with live streams, it seemed like discontinuity errors or etc could cause the problem.

I suggest adding an option to ignore these errors and output whatever fingerprint data is available. I implemented it where it's needed, but this bool could be tested throughout:
[ignore_errors.txt](https://github.com/acoustid/chromaprint/files/649317/ignore_errors.txt)

**Comment by lalinsky** [comment]
I'm not sure if this is a good idea as is. I'd like to understand where do the errors come from. If it's something like disconnects, those could be handled explicitly. With your changes, the code could end up looping forever with just errors.

**Comment by elliotd123** [comment]
I probably didn't implement it well necessarily. I don't see the endless loop that you're talking about though - if there's an error, it should break from the loop and output the data that it already has instead of exiting with a status of 2. That's what I was going for anyway.

**Comment by lalinsky** [comment]
You are right. I misunderstood the code. I have committed a slight variation of your patch to master. By default, this will now exit with status of 3 if there is an error, but it produced some output. You can also use -ignore-errors to turn that status code into 0.
