### ISSUE TITLE
Issue with fingerprinting MP3

### ISSUE THREAD

**Issue by CyberSinh** [acoustid/chromaprint#34]
Hi Lukas,

I try to compute fingerprint the following MP3 file with fpcalc but without success (rename ZIP to MP3):
[chromaprint_issue.mp3.zip](https://github.com/acoustid/chromaprint/files/670025/chromaprint_issue.mp3.zip)

fpcalc returns nothing in the console. And the chromaprint library fails after calling the avcodec_decode_audio4 function.

However, the file seems to be perfectly playable and ffprobe doesn't report any issue.

Do you know why the file cannot be fingerprinted by chromaprint?

Thanks.

**Comment by lalinsky** [comment]
I can't reproduce this. I have tried compiling 1.4.0, 1.4.1 and the latest master against the default FFmpeg from Ubuntu 16.04 and I have tried running fpcalc 1.4.1 from the official binaries (which use FFmpeg 3.2.2) and in all cases it returns the correct output.

**Comment by CyberSinh** [comment]
You will below a screencast showing the issue under Windows:
![issue_chromaprint2](https://cloud.githubusercontent.com/assets/10407531/21520958/d7cc1c5a-ccf8-11e6-9adc-2227fccfd2f7.gif)

**Comment by lalinsky** [comment]
Please try that with 1.4.1. The version from the screenshot has a known bug that causes this.

**Comment by CyberSinh** [comment]
Yes, it seems to work fine now. Thank you very much!

**Comment by CyberSinh** [comment]
The file is correctly fingerprinted if I use the default length in fpcalc.
But if I try to fingerprint the whole file (fpcalc -length 0 ...), I get the following error message:
ERROR: Error decoding audio frame (Invalid data found when processing input).

**Comment by lalinsky** [comment]
The last frame in the file was broken. I have changed the code to allow one broken frame.

**Comment by CyberSinh** [comment]
Thank you Lukas!
