### ISSUE TITLE
NDEBUG is not a macro defined in Release mode by MSVC

### ISSUE THREAD

**Issue by CyberSinh** [acoustid/chromaprint#35]
Hi Lukas,

It seems that MSVC doesn't define the NDEBUG macro under Release mode, so the preprocessor condition in the src/debug.h and src/image.h is always false:

```C
#ifdef(NDEBUG)

#endif
```

Perhaps we could use #ifndef(_DEBUG) instead of #ifdef(NDEBUG), at least when the compiler is MSVC?

Regards,

Cyber Sinh

**Comment by lalinsky** [comment]
NDEBUG is not meant to be defined by MSVC, it's defined by CMake and used by the standard library.

Are you building the code with CMake or you included them into your own Visual Studio project? If the later, you need to define NDEBUG yourself.

https://github.com/Kitware/CMake/blob/095279bc94c81c4076de20474f1d3dd186764388/Modules/Platform/Windows-MSVC.cmake#L295

**Comment by CyberSinh** [comment]
You're right Lukas!

With the native CMake support in the upcoming Visual Studio 2017, this macro will be managed automatically by Visual Studio. No need to play with the CMake command line or to generate Visual Studio project... Just open the folder containing the source code, right-clic on the CMakeList.txt, then build/install...

Thanks.
