### ISSUE TITLE
Cannot find FFMpeg installation

### ISSUE THREAD

**Issue by fillobotto** [acoustid/chromaprint#36]
As the title says, I get configuration error while try to `cmake`.

> filippo@filippo-VirtualBox:~/Scrivania/chromaprint$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=ON .
> FFTW3 lib not found. Set FFTW3_DIR to find it.
> -- Using kissfft for FFT calculations
> -- Building without audio conversion support, please install FFmpeg with libswresample
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> FFMPEG_LIBAVCODEC_INCLUDE_DIRS
>    used as include directory in directory /home/filippo/Scrivania/chromaprint/src/cmd
>    used as include directory in directory /home/filippo/Scrivania/chromaprint/src/cmd
> FFMPEG_LIBAVFORMAT_INCLUDE_DIRS
>    used as include directory in directory /home/filippo/Scrivania/chromaprint/src/cmd
>    used as include directory in directory /home/filippo/Scrivania/chromaprint/src/cmd
> FFMPEG_LIBAVUTIL_INCLUDE_DIRS
>    used as include directory in directory /home/filippo/Scrivania/chromaprint/src/cmd
>    used as include directory in directory /home/filippo/Scrivania/chromaprint/src/cmd
> 
> -- Configuring incomplete, errors occurred!

However I installed ffmpeg 0.8.17 (in its default location) on my machine and it's working correctly.
I'm running Ubuntu 12.04.

**Comment by lalinsky** [comment]
You need the dev packages, i.e. `libavcodec-dev`, `libavformat-dev`, `libavutil-dev`.

However, I'm not sure if the old version on Ubuntu 12.04 is going to work.

**Comment by fillobotto** [comment]
Forgot to leave a feedback: moving to 14.04 and installing the suite suggested here https://github.com/acoustid/chromaprint-build/blob/master/Dockerfile solved that error.
