### ISSUE TITLE
How to create release builds?

### ISSUE THREAD

**Issue by rednoah** [acoustid/chromaprint#38]
Hi Lukáš,

I've been experimenting with compiling fpcalc for different platforms myself. Which scripts or compiler options are you using to create the release packages?

The official (release binaries)[https://acoustid.org/chromaprint] are all a few MB large. But when I compile myself with the instructions on the `README.md` it's barely 100 KB so I'm probably missing some static dependencies but I'm not sure which compiler options I need to include all of those in the binary.

Cheers, Reinhard

**Comment by lalinsky** [comment]
This is the build process: https://github.com/acoustid/chromaprint/blob/master/.gitlab-ci.yml

It's using the scripts from https://github.com/acoustid/chromaprint/tree/master/package and my static FFmpeg builds from https://code.oxygene.sk/acoustid/ffmpeg-build.

**Comment by lalinsky** [comment]
Oh, and I'm using this Docker image with all the necessary build tools pre-installed:

https://code.oxygene.sk/acoustid/chromaprint-build/blob/master/Dockerfile

**Comment by rednoah** [comment]
Thanks. Looking at the CI and docker scripts should get me a bit closer.

**Comment by lalinsky** [comment]
Btw, let me know if you need builds for other platforms. I'll try to include them in the official releases if I can build them automatically.

**Comment by lalinsky** [comment]
There already are Linux `armhf` builds. https://acoustid.org/chromaprint

Or do you want them for Android?

**Comment by rednoah** [comment]
My bad. I hadn't noticed. Just tried and it works perfectly out of the box.

**Comment by geecko86** [comment]
I do want them for Android. There's a repo on BitBucket but it's severely out of date at this point.

@lalinsky  What do you recommend for building Chromaprint for Android? Preferably with ffmpeg

**Comment by lalinsky** [comment]
I'm sorry, but I do not have enough experience with Android development to help much with this. I'm fine running the Android build in my CI system and providing them for releases, but I can't work on the build scripts.

You could use something like https://github.com/WritingMinds/ffmpeg-android to adapt https://github.com/acoustid/ffmpeg-build to Android. Once you have that, building Chromaprint should be easy. The question is how you use it. The best solution would be to add a full JNI wrapper to this repo, but once again, I'm not the best person to do that. I'm more than happy to help anyone doing that and merging it here.

**Comment by geecko86** [comment]
@lalinsky 
I'd be happy to help with that. Will send a pull request ASAP.

Before I do that, though, I just want to make sure I'm headed the right way. Here's a question for you.

A moment ago, I compiled [koendv/FFmpeg-Audio-Android](https://github.com/koendv/FFmpeg-Audio-Android). I was able to choose which version of ffmpeg I wanted to use. I read somewhere that ffmpeg 3.3+ is required for recent versions of Android, so I went with `n3.3.6`. Building the project created a build directory which contained the following:

```
build
├── arm64-v8a
│   ├── bin
│   │   └── ffmpeg
│   ├── include
│   │   ├── libavcodec
│   │   │   ├── avcodec.h
│   │   │   ├── avdct.h
│   │   │   ├── avfft.h
│   │   │   ├── d3d11va.h
│   │   │   ├── dirac.h
│   │   │   ├── dv_profile.h
│   │   │   ├── dxva2.h
│   │   │   ├── jni.h
│   │   │   ├── mediacodec.h
│   │   │   ├── qsv.h
│   │   │   ├── vaapi.h
│   │   │   ├── vda.h
│   │   │   ├── vdpau.h
│   │   │   ├── version.h
│   │   │   ├── videotoolbox.h
│   │   │   ├── vorbis_parser.h
│   │   │   └── xvmc.h
│   │   ├── libavfilter
│   │   │   ├── avfiltergraph.h
│   │   │   ├── avfilter.h
│   │   │   ├── buffersink.h
│   │   │   ├── buffersrc.h
│   │   │   └── version.h
│   │   ├── libavformat
│   │   │   ├── avformat.h
│   │   │   ├── avio.h
│   │   │   └── version.h
│   │   ├── libavutil
│   │   │   ├── adler32.h
│   │   │   ├── aes_ctr.h
│   │   │   ├── aes.h
│   │   │   ├── attributes.h
│   │   │   ├── audio_fifo.h
│   │   │   ├── avassert.h
│   │   │   ├── avconfig.h
│   │   │   ├── avstring.h
│   │   │   ├── avutil.h
│   │   │   ├── base64.h
│   │   │   ├── blowfish.h
│   │   │   ├── bprint.h
│   │   │   ├── bswap.h
│   │   │   ├── buffer.h
│   │   │   ├── camellia.h
│   │   │   ├── cast5.h
│   │   │   ├── channel_layout.h
│   │   │   ├── common.h
│   │   │   ├── cpu.h
│   │   │   ├── crc.h
│   │   │   ├── des.h
│   │   │   ├── dict.h
│   │   │   ├── display.h
│   │   │   ├── downmix_info.h
│   │   │   ├── error.h
│   │   │   ├── eval.h
│   │   │   ├── ffversion.h
│   │   │   ├── fifo.h
│   │   │   ├── file.h
│   │   │   ├── frame.h
│   │   │   ├── hash.h
│   │   │   ├── hmac.h
│   │   │   ├── hwcontext_cuda.h
│   │   │   ├── hwcontext_dxva2.h
│   │   │   ├── hwcontext.h
│   │   │   ├── hwcontext_qsv.h
│   │   │   ├── hwcontext_vaapi.h
│   │   │   ├── hwcontext_vdpau.h
│   │   │   ├── imgutils.h
│   │   │   ├── intfloat.h
│   │   │   ├── intreadwrite.h
│   │   │   ├── lfg.h
│   │   │   ├── log.h
│   │   │   ├── lzo.h
│   │   │   ├── macros.h
│   │   │   ├── mastering_display_metadata.h
│   │   │   ├── mathematics.h
│   │   │   ├── md5.h
│   │   │   ├── mem.h
│   │   │   ├── motion_vector.h
│   │   │   ├── murmur3.h
│   │   │   ├── opt.h
│   │   │   ├── parseutils.h
│   │   │   ├── pixdesc.h
│   │   │   ├── pixelutils.h
│   │   │   ├── pixfmt.h
│   │   │   ├── random_seed.h
│   │   │   ├── rational.h
│   │   │   ├── rc4.h
│   │   │   ├── replaygain.h
│   │   │   ├── ripemd.h
│   │   │   ├── samplefmt.h
│   │   │   ├── sha512.h
│   │   │   ├── sha.h
│   │   │   ├── spherical.h
│   │   │   ├── stereo3d.h
│   │   │   ├── tea.h
│   │   │   ├── threadmessage.h
│   │   │   ├── timecode.h
│   │   │   ├── time.h
│   │   │   ├── timestamp.h
│   │   │   ├── tree.h
│   │   │   ├── twofish.h
│   │   │   ├── version.h
│   │   │   └── xtea.h
│   │   ├── libpostproc
│   │   │   ├── postprocess.h
│   │   │   └── version.h
│   │   └── libswresample
│   │       ├── swresample.h
│   │       └── version.h
│   ├── lib
│   │   ├── libavcodec.a
│   │   ├── libavfilter.a
│   │   ├── libavformat.a
│   │   ├── libavutil.a
│   │   ├── libpostproc.a
│   │   ├── libswresample.a
│   │   └── pkgconfig
│   │       ├── libavcodec.pc
│   │       ├── libavfilter.pc
│   │       ├── libavformat.pc
│   │       ├── libavutil.pc
│   │       ├── libpostproc.pc
│   │       └── libswresample.pc
│   └── share
│       └── ffmpeg
│           ├── examples
│           │   ├── avio_dir_cmd.c
│           │   ├── avio_reading.c
│           │   ├── decode_audio.c
│           │   ├── decode_video.c
│           │   ├── demuxing_decoding.c
│           │   ├── encode_audio.c
│           │   ├── encode_video.c
│           │   ├── extract_mvs.c
│           │   ├── filter_audio.c
│           │   ├── filtering_audio.c
│           │   ├── filtering_video.c
│           │   ├── http_multiclient.c
│           │   ├── Makefile
│           │   ├── metadata.c
│           │   ├── muxing.c
│           │   ├── qsvdec.c
│           │   ├── README
│           │   ├── remuxing.c
│           │   ├── resampling_audio.c
│           │   ├── scaling_video.c
│           │   ├── transcode_aac.c
│           │   └── transcoding.c
│           ├── ffprobe.xsd
│           ├── libvpx-1080p50_60.ffpreset
│           ├── libvpx-1080p.ffpreset
│           ├── libvpx-360p.ffpreset
│           ├── libvpx-720p50_60.ffpreset
│           └── libvpx-720p.ffpreset
├── armeabi-v7a
├── armeabi-v7a-neon
├── x86
└── x86-64
```

The contents of the 4 other architectures are similar to the first one, I didn't include them for the sake of brevity. All binaries are Android binaries. **Does this look like what we're looking for?**

Now, having close to no experience with building ffmpeg or chromaprint, I just wanted to double check that I was headed in the right direction. My plan is to adapt [acoustid/ffmpeg-build](https://github.com/acoustid/ffmpeg-build) to use [koendv/FFmpeg-Audio-Android](https://github.com/koendv/FFmpeg-Audio-Android), then send a pull request to this repo that makes it possible to build chromaprint with FFmpeg-Android using the Android toolchain and, finally, do what's necessary regarding the jniwrapper. 

I know I'm kind of repeating what you just said with - but I'd rather be safe than sorry.

**Comment by lalinsky** [comment]
Yes, that all looks good.

It seems that Android NDK includes native CMake support, so building Chromaprint might not be that hard.

One problem you will hit is that Chromaprint by itself does not include support for audio file decoding. So you will have the choice of either moving that functionality to your app, or including it in Chromaprint. I know some people have a fork of Chromaprint with fpcalc-like functionality in the library itself. I'm not sure what is the best solution there.

**Comment by geecko86** [comment]
Sorry I might have talked about "chromaprint" when really what I want at the end of the day is essentially to output a `libfpcalc.so` which I can use to get access to the fpcalc command. That should be possible, right? It's what [phorton1/chromaprint](https://bitbucket.org/phorton1/chromaprint) does.

**Comment by lalinsky** [comment]
Yes, it's possible, but it will require some refactoring.

**Comment by geecko86** [comment]
Alright, I solved it by specifying `CMAKE_FIND_ROOT_PATH`. CMake was successfully able to configure the project.

However the `make` fails at 100%:

```
[100%] Linking CXX executable fpcalc
/home/geecko/.builds/FFmpeg-Audio-Android/build/armeabi-v7a-neon/lib/libavformat.a(id3v2.o):id3v2.c:function id3v2_parse: error: undefined reference to 'uncompress'
/home/geecko/.builds/FFmpeg-Audio-Android/build/armeabi-v7a-neon/lib/libavformat.a(matroskadec.o):matroskadec.c:function matroska_decode_buffer.isra.10: error: undefined reference to 'inflateInit_'
/home/geecko/.builds/FFmpeg-Audio-Android/build/armeabi-v7a-neon/lib/libavformat.a(matroskadec.o):matroskadec.c:function matroska_decode_buffer.isra.10: error: undefined reference to 'inflate'
/home/geecko/.builds/FFmpeg-Audio-Android/build/armeabi-v7a-neon/lib/libavformat.a(matroskadec.o):matroskadec.c:function matroska_decode_buffer.isra.10: error: undefined reference to 'inflateEnd'
/home/geecko/.builds/FFmpeg-Audio-Android/build/armeabi-v7a-neon/lib/libavformat.a(matroskadec.o):matroskadec.c:function matroska_decode_buffer.isra.10: error: undefined reference to 'inflateEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [src/cmd/CMakeFiles/fpcalc.dir/build.make:100: src/cmd/fpcalc] Error 1
make[1]: *** [CMakeFiles/Makefile2:246: src/cmd/CMakeFiles/fpcalc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```
