### ISSUE TITLE
chroma features

### ISSUE THREAD

**Issue by dogarrhea** [acoustid/chromaprint#40]
I would like to leverage the chroma feature functionality described at https://oxygene.sk/2011/01/how-does-chromaprint-work/ but am not sure where to look in the repository.

Specifically,  I would like to access the array/pointer or whatever structure this is being held in when chromaprint runs.  Any guidance as to where to find this would be appreciated.

**Comment by lalinsky** [comment]
It's really not practical to parts of Chromaprint like this. I didn't know much about what I was doing then I was designing the algorithm and most of the stuff it not actually correct. It works for audio fingerprinting, but it's not musically correct. You are better of using of the generic MIR library for things like things.
