### ISSUE TITLE
FFmpeg not found when cross-compiling for Synology

### ISSUE THREAD

**Issue by ymartin59** [acoustid/chromaprint#42]
When upgrading SynoCommunity Chromaprint from 1.3.1 to 1.4.2, I faced troubles because of `find_package(FFmpeg)` failing to find `stdint.h` with enlisted path. I wonder if this issue may be generic in any cross-compilation context.

As a work-around, I have commented last condition `AND FFMPEG_STDINT_INCLUDE_DIR` at https://github.com/acoustid/chromaprint/blob/master/cmake/modules/FindFFmpeg.cmake#L111

Original makefile for Chromaprint 1.3.1: https://github.com/SynoCommunity/spksrc/blob/master/cross/chromaprint/Makefile

Patch I applied to get Chromaprint 1.4.2 configured properly:  `cross/chromaprint/patches/002-cmake-find-ffmpeg.patch`

``` 
--- cmake/modules/FindFFmpeg.cmake.orig	2017-07-30 09:38:01.979775537 +0200
+++ cmake/modules/FindFFmpeg.cmake	2017-07-30 09:51:43.141003104 +0200
@@ -108,7 +108,7 @@
 
 SET(FFMPEG_FOUND "NO")
 # Note we don't check FFMPEG_LIBSWSCALE_FOUND here, it's optional.
-IF   (FFMPEG_LIBAVFORMAT_FOUND AND FFMPEG_LIBAVCODEC_FOUND AND FFMPEG_LIBAVUTIL_FOUND AND FFMPEG_STDINT_INCLUDE_DIR)
+IF   (FFMPEG_LIBAVFORMAT_FOUND AND FFMPEG_LIBAVCODEC_FOUND AND FFMPEG_LIBAVUTIL_FOUND)
 
     SET(FFMPEG_FOUND "YES")
```

Is there better option to support cross-compiling toolchains which provides their own `stdint.h` and so not found in usual system locations ?
Thank you in advance for your help

**Comment by lalinsky** [comment]
Thanks, just removing the check should be fine.
