### ISSUE TITLE
[question] How to make the fingerprints usable when recording via low quality microphones?

### ISSUE THREAD

**Issue by halaei** [acoustid/chromaprint#47]
First of all thanks for the amazing project.
Currently, we are using `fpcal` to detect near-identical duplicates in a database of high quality music files. However, we were not successful to use it in order to detect musics recorded by low quality mobile microphones. Any help on how should we approach this problem?
Thanks.

**Comment by lalinsky** [comment]
This is not possible. The fingerprints generated by this library are not detailed enough to allow that kind of matching.
