### ISSUE TITLE
Cannot find source file INTERFACE in src/cmd/CMakeLists.txt:27

### ISSUE THREAD

**Issue by kvishnivetsky** [acoustid/chromaprint#48]
Hi!
I'm trying to build under **CentOS 7 x86_64** **cmake version 2.8.12.2** and following error is accured:

```
cmake -DFFTW3_DIR=xxxxxxxxxx -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=ON

-- Using avfft for FFT calculations
-- Using swresample for audio conversion
-- Configuring done
**CMake Error at src/cmd/CMakeLists.txt:27 (add_library):**
  Cannot find source file:

    **INTERFACE**

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

```

What am I doing wrong?

**Comment by lalinsky** [comment]
Maybe the minimum version of CMake specified in CMakeLists.txt is out of date. I'll bump it to require at least CMake 3.x which should support interface libraries according to the documentation.

**Comment by kvishnivetsky** [comment]
Thanks!
