### ISSUE TITLE
Building on OS X

### ISSUE THREAD

**Issue by kevinkilroy** [acoustid/chromaprint#55]
Hi, Trying to build on OS X 10.13.6 fails on linking the fpcalc lib

`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/ -DFFT_LIB=vdsp .
make`

Output:
`[ 81%] Built target chromaprint_objs
[ 90%] Built target chromaprint
[ 95%] Linking CXX executable fpcalc
Undefined symbols for architecture x86_64:
  "_AudioConverterDispose", referenced from:
      _ffat_close_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_close_encoder in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterFillComplexBuffer", referenced from:
      _ffat_decode in libavcodec.a(audiotoolboxdec.o)
      _ffat_encode in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterGetProperty", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterGetPropertyInfo", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterNew", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterReset", referenced from:
      _ffat_decode_flush in libavcodec.a(audiotoolboxdec.o)
      _ffat_encode_flush in libavcodec.a(audiotoolboxenc.o)
  "_AudioConverterSetProperty", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
      _ffat_init_encoder in libavcodec.a(audiotoolboxenc.o)
  "_AudioFormatGetProperty", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
  "_AudioFormatGetPropertyInfo", referenced from:
      _ffat_create_decoder in libavcodec.a(audiotoolboxdec.o)
  "_BZ2_bzDecompress", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_BZ2_bzDecompressEnd", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_BZ2_bzDecompressInit", referenced from:
      _matroska_decode_buffer in libavformat.a(matroskadec.o)
  "_CFArrayCreate", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_CFArrayCreateMutableCopy", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_CFArrayGetCount", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _import_pem in libavformat.a(tls_securetransport.o)
  "_CFArrayGetValueAtIndex", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _tls_open in libavformat.a(tls_securetransport.o)
  "_CFArraySetValueAtIndex", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_CFBooleanGetValue", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CFDataCreate", referenced from:
      _ff_videotoolbox_avcc_extradata_create in libavcodec.a(videotoolbox.o)
      _ff_videotoolbox_hvcc_extradata_create in libavcodec.a(videotoolbox.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
      _import_pem in libavformat.a(tls_securetransport.o)
  "_CFDictionaryCreate", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_CFDictionaryCreateMutable", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_CFDictionaryGetValueIfPresent", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CFDictionarySetValue", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_CFNumberCreate", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_CFRelease", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_close in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_output_callback in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_uninit in libavcodec.a(videotoolbox.o)
      ...
  "_CFRetain", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_output_callback in libavcodec.a(videotoolboxenc.o)
      _tls_open in libavformat.a(tls_securetransport.o)
  "_CFStringCreateWithCString", referenced from:
      _import_pem in libavformat.a(tls_securetransport.o)
  "_CMBlockBufferCopyDataBytes", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CMBlockBufferCreateWithMemoryBlock", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_CMSampleBufferCreate", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_CMSampleBufferGetDataBuffer", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetDecodeTimeStamp", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetFormatDescription", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_output_callback in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetPresentationTimeStamp", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetSampleAttachmentsArray", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CMSampleBufferGetTotalSampleSize", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_CMTimeMake", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_CMVideoFormatDescriptionCreate", referenced from:
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_CMVideoFormatDescriptionGetH264ParameterSetAtIndex", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_CVBufferSetAttachments", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_CVPixelBufferCreateWithPlanarBytes", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_CVPixelBufferGetBaseAddress", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferGetBaseAddressOfPlane", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferGetBytesPerRow", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferGetBytesPerRowOfPlane", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferGetHeight", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferGetPixelFormatType", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferGetPlaneCount", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferGetWidth", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferIsPlanar", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferLockBaseAddress", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
  "_CVPixelBufferRelease", referenced from:
      _videotoolbox_buffer_release in libavcodec.a(videotoolbox.o)
      _ff_videotoolbox_uninit in libavcodec.a(videotoolbox.o)
      _videotoolbox_uninit in libavcodec.a(videotoolbox.o)
      _videotoolbox_decoder_callback in libavcodec.a(videotoolbox.o)
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_CVPixelBufferRetain", referenced from:
      _videotoolbox_decoder_callback in libavcodec.a(videotoolbox.o)
  "_CVPixelBufferUnlockBaseAddress", referenced from:
      _vt_map_frame in libavutil.a(hwcontext_videotoolbox.o)
      _vt_unmap in libavutil.a(hwcontext_videotoolbox.o)
  "_SSLClose", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
      _tls_close in libavformat.a(tls_securetransport.o)
  "_SSLCopyPeerTrust", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLCreateContext", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLGetBufferedReadSize", referenced from:
      _tls_read in libavformat.a(tls_securetransport.o)
  "_SSLHandshake", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLRead", referenced from:
      _tls_read in libavformat.a(tls_securetransport.o)
  "_SSLSetCertificate", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLSetConnection", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLSetIOFuncs", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLSetPeerDomainName", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLSetSessionOption", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SSLWrite", referenced from:
      _tls_write in libavformat.a(tls_securetransport.o)
  "_SecIdentityCreate", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SecItemImport", referenced from:
      _import_pem in libavformat.a(tls_securetransport.o)
  "_SecTrustEvaluate", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_SecTrustSetAnchorCertificates", referenced from:
      _tls_open in libavformat.a(tls_securetransport.o)
  "_VTCompressionSessionCompleteFrames", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_close in libavcodec.a(videotoolboxenc.o)
  "_VTCompressionSessionCreate", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_VTCompressionSessionEncodeFrame", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_VTCompressionSessionPrepareToEncodeFrames", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_VTDecompressionSessionCreate", referenced from:
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionDecodeFrame", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionInvalidate", referenced from:
      _videotoolbox_uninit in libavcodec.a(videotoolbox.o)
      _av_videotoolbox_default_free in libavcodec.a(videotoolbox.o)
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_VTDecompressionSessionWaitForAsynchronousFrames", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_VTSessionCopyProperty", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_VTSessionSetProperty", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "___CFConstantStringClassReference", referenced from:
      CFString in libavcodec.a(videotoolboxenc.o)
      CFString in libavcodec.a(videotoolboxenc.o)
      CFString in libavcodec.a(videotoolboxenc.o)
      CFString in libavcodec.a(videotoolboxenc.o)
      CFString in libavcodec.a(videotoolboxenc.o)
      CFString in libavcodec.a(videotoolboxenc.o)
      CFString in libavcodec.a(videotoolboxenc.o)
      ...
  "_iconv", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
  "_iconv_close", referenced from:
      _avcodec_open2 in libavcodec.a(utils.o)
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
  "_iconv_open", referenced from:
      _avcodec_open2 in libavcodec.a(utils.o)
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
  "_kCFAllocatorDefault", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
      _ff_videotoolbox_avcc_extradata_create in libavcodec.a(videotoolbox.o)
      _ff_videotoolbox_hvcc_extradata_create in libavcodec.a(videotoolbox.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
      ...
  "_kCFAllocatorNull", referenced from:
      _videotoolbox_common_end_frame in libavcodec.a(videotoolbox.o)
  "_kCFBooleanFalse", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kCFBooleanTrue", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCFCopyStringDictionaryKeyCallBacks", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_kCFTypeArrayCallBacks", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kCFTypeDictionaryKeyCallBacks", referenced from:
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCFTypeDictionaryValueCallBacks", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms", referenced from:
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCMSampleAttachmentKey_NotSync", referenced from:
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
  "_kCMTimeIndefinite", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_frame in libavcodec.a(videotoolboxenc.o)
      _vtenc_close in libavcodec.a(videotoolboxenc.o)
  "_kCMTimeInvalid", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferColorPrimariesKey", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferColorPrimaries_ITU_R_709_2", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferGammaLevelKey", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferPixelAspectRatioHorizontalSpacingKey", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferPixelAspectRatioVerticalSpacingKey", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferTransferFunctionKey", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferTransferFunction_ITU_R_709_2", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferTransferFunction_SMPTE_240M_1995", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferTransferFunction_UseGamma", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferYCbCrMatrixKey", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferYCbCrMatrix_ITU_R_601_4", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferYCbCrMatrix_ITU_R_709_2", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kCVImageBufferYCbCrMatrix_SMPTE_240M_1995", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kCVPixelBufferHeightKey", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey", referenced from:
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCVPixelBufferIOSurfacePropertiesKey", referenced from:
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCVPixelBufferPixelFormatTypeKey", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kCVPixelBufferWidthKey", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _videotoolbox_start in libavcodec.a(videotoolbox.o)
  "_kVTCompressionPropertyKey_AllowFrameReordering", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_AverageBitRate", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_ColorPrimaries", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_DataRateLimits", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_MaxKeyFrameInterval", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_MoreFramesAfterEnd", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_MoreFramesBeforeStart", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_PixelAspectRatio", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_ProfileLevel", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_TransferFunction", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTCompressionPropertyKey_YCbCrMatrix", referenced from:
      _vtenc_create_encoder in libavcodec.a(videotoolboxenc.o)
  "_kVTEncodeFrameOptionKey_ForceKeyFrame", referenced from:
      _vtenc_send_frame in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_1_3", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_3_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_3_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_3_2", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Baseline_4_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_High_5_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_3_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_3_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_3_2", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_4_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_4_1", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_kVTProfileLevel_H264_Main_5_0", referenced from:
      _vtenc_init in libavcodec.a(videotoolboxenc.o)
  "_lzma_code", referenced from:
      _decode_frame in libavcodec.a(tiff.o)
  "_lzma_end", referenced from:
      _decode_frame in libavcodec.a(tiff.o)
  "_lzma_stream_decoder", referenced from:
      _decode_frame in libavcodec.a(tiff.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/cmd/fpcalc] Error 1
make[1]: *** [src/cmd/CMakeFiles/fpcalc.dir/all] Error 2
make: *** [all] Error 2`

Does it require the CoreAudio framework to be passed as a library/framework to ld? If so can you provide example how to do that.?

Thanks,

**Comment by dcam0050** [comment]
For those still struggling with this issue, going through configure for ffmpeg revealed the answer. You need to add frameworks to your LDFLAGS environment variable as follows:
`-Wl,-framework,CoreFoundation -Wl,-framework,Security -Wl,-framework,VideoToolbox -Wl,-framework,CoreMedia -Wl,-framework,CoreVideo` some will need more frameworks, others will need to link with less but a good indicator of which framework is needed can be found in the names of the missing symbols:

_CF* - CoreFoundation
_VT* - VideoToolbox
and so on. Hope this helps

**Comment by artkiver** [comment]
I would be curious what compiler flags are recommended currently (1.5.1)

e.g.

% cmake -DFFT_LIB=vDSP .

results in:
-- Could not find FFMPEG
CMake Error at CMakeLists.txt:155 (message):
  No FFT library found

cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/ -DFFT_LIB=vdsp -Wl,-framework,CoreFoundation -Wl,-framework,Security -Wl,-framework,VideoToolbox -Wl,-framework,CoreMedia -Wl,-framework,CoreVideo .

Also seems to result in:

CMake Error in src/cmd/CMakeLists.txt:
  Found relative path while evaluating include directories of "fpcalc":

    "FFMPEG_LIBAVFORMAT_INCLUDE_DIRS-NOTFOUND"


So, I am wondering, if the README.md still states:

"FFmpeg is preferred on all systems except for macOS, where you should use
the standard vDSP framework. These are the fastest options."

Is that accurate?

I started looking into this because the MacPort for chromaprint has an inordinate number of dependencies. I thought, perhaps by using vDSP (for which there is no variant in the MacPort currently) perhaps I could obviate some of those dependencies?

This ticket is the closest thing I can find to anyone running into similar build issues though.

**Comment by lalinsky** [comment]
@artkiver If you enable `BUILD_TOOLS`, you automatically need most of the FFmpeg libraries. The `FFT_LIB=vdsp` option only means that the library will use vDSP (from the Accelerate framework) for FFT calculations, but the `fpcalc` still needs FFmpeg for audio decoding.

If you just want to use `fpcalc`, download the OS X binary from https://acoustid.org/chromaprint. Those binaries are built with stopped down version of FFmpeg, only capable of decoding audio files, which is why they are much smaller than what typical package distros include.

If you want chromaprint as a library, you can set `-DBUILD_TOOLS=OFF` (it's the default) and then it will build with FFmpeg.
