### ISSUE TITLE
Questions regarding Chromaprint

### ISSUE THREAD

**Issue by DonaldTsang** [acoustid/chromaprint#56]
1. Is it possible to match music that are not perfect octaves higher, but instead 1~11 half-steps higher? In that case the matching will have to be done 12 times.
2. Is it possible to match music that has been slowed down or sped up (e.g. digital music vs slow record player), in that case beats-per-minutes should be factored in.
3. Is it possible to match music like soundhound or shazam, where a recording in a mall or other slightly noisy location can have matches (e.g. [Python](https://willdrevo.com/fingerprinting-and-audio-recognition-with-python/) or [JavaScript](https://github.com/adblockradio/stream-audio-fingerprint))

**Comment by lalinsky** [comment]
No, none of these are really possible.
