### ISSUE TITLE
Linking error, compilation fails.

### ISSUE THREAD

**Issue by sypai** [acoustid/chromaprint#60]
I am trying to compile chromaprint and I am getting this error. 

> Scanning dependencies of target chromaprint_objs
> [ 86%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fft_lib_avfft.cpp.o
> [ 86%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fft.cpp.o
> [ 86%] Built target chromaprint_objs
> [ 86%] Linking CXX shared library libchromaprint.so
> /usr/bin/ld: /usr/local/lib/libavcodec.a(fft.o): relocation R_X86_64_PC32 against symbol `ff_cos_32' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> src/CMakeFiles/chromaprint.dir/build.make:132: recipe for target 'src/libchromaprint.so.1.4.4' failed
> make[2]: *** [src/libchromaprint.so.1.4.4] Error 1
> CMakeFiles/Makefile2:153: recipe for target 'src/CMakeFiles/chromaprint.dir/all' failed
> make[1]: *** [src/CMakeFiles/chromaprint.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> 

I tried using an older version of FFmpeg still the problem persists.
Any help would be appreciated.

**Comment by bochecha** [comment]
```
 /usr/bin/ld: /usr/local/lib/libavcodec.a(fft.o): relocation R_X86_64_PC32 against symbol `ff_cos_32' can not be used when making a shared object; recompile with -fPIC
```

You need to compile with `-fPIC` as mentioned in the error message.
