### ISSUE TITLE
Cannot build with mingw-w64 toolchains

### ISSUE THREAD

**Issue by dbogdanov** [acoustid/chromaprint#61]
It appears the cross-compilation instructions for Windows are outdated: the toolchain `i586-mingw32msvc` is not available on newer platforms, at least on Ubuntu 19.04. 

It should be possible to build using the current toolchains available in `mingw-w64` package, which is what is available on Ubuntu. 

Trying to build with `i686-w64-mingw32-gcc` / `i686-w64-mingw32-g++` fails with compilation errors. I haven't found any other appropriate alternative in that package... Or am I doing something wrong?

**Comment by lalinsky** [comment]
I'm not sure what's the issue, but the official packages are build with mingw-w64, so you can have a look at the build scripts in this repo.
