### ISSUE TITLE
Seg fault when using CHROMAPRINT_ALGORITHM_TEST4 with ffmpeg

### ISSUE THREAD

**Issue by talih0** [acoustid/chromaprint#63]
As of commit 21b2442f (chromaprint lib) calling chromaprint from ffmpeg with CHROMAPRINT_ALGORITHM_TEST3
causes a seg fault. To reproduce: 

$ ffmpeg -f lavfi -i sine=d=20,asetnsamples=n=1000 -f chromaprint -algorithm 2 -
...
[1]    3691 segmentation fault (core dumped)  ./ffmpeg -f lavfi -i sine=d=20,asetnsamples=n=1000 -f chromaprint -algorithm

AFAICT this is because FFT frame is set to zero in the configuration of the algorithm. Setting frame size to a reasonable value will probably solve the issue. Let me know if you agree and I can submit a pull request.

**Comment by talih0** [comment]
I get the same seg fault when using fpcalc with algorithm 3 option
./fpcalc -algorithm 3 out.mp3
[1]    13296 segmentation fault (core dumped)  ./fpcalc -algorithm 3 out.mp3

**Comment by talih0** [comment]
ping

**Comment by lalinsky** [comment]
Yes, it looks like the default FFT frame size is not set for those configurations.
