### ISSUE TITLE
[macOS] The binary uses an SDK older than the 10.9 SDK.

### ISSUE THREAD

**Issue by rednoah** [acoustid/chromaprint#67]
Since Apple decided to make [Notarization](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution) extra strict this month, we can't bundle `fpcalc` anymore due to:
```
The binary uses an SDK older than the 10.9 SDK.
```
[Resolving Common Notarization Issues](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues) has a section on this issue, but their help is limited to Xcode GUI clickly-clicky. Haven't had much luck fixing this via `cmake` options.

**Comment by rednoah** [comment]
Fixed it by adding `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.10` to my build.

**Comment by lalinsky** [comment]
The next version will use a more recent SDK. Hope to release it soon.

**Comment by rednoah** [comment]
Cheers. Much appreciated.
