### ISSUE TITLE
fpcalc canot be notarized on MacOS because uses an SDK older than the 10.9 SDK

### ISSUE THREAD

**Issue by ijabz** [acoustid/chromaprint#69]
Apple tightened the restrictions on notarization on Feb 5th 2020 and this includes not being able to notarize any executable built against and SDK earlier then 10.9  - https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues

The latest version of fpcalc (1.4.3) fails with this error

Below see output of failed notarization attempt with SongKong bundle due to the fpcalc executable, (if this is removed from the bundle then notarize passes).

{
  "logFormatVersion": 1,
  "jobId": "8ce78f08-9981-4b89-b653-1fba82c9a8d2",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "songkong-osx.dmg",
  "uploadDate": "2020-04-14T10:41:21Z",
  "sha256": "dfbd6cc6933e1a017978870512ccfb306b847c22563b84cd20c2120fe2043e9f",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "songkong-osx.dmg/SongKong.app/Contents/MacOS/fpcalc",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
}

Could you please rebuild and release fpcalc against later MacOS

**Comment by lalinsky** [comment]
This is now fixed in 1.5.0 - https://github.com/acoustid/chromaprint/releases/tag/v1.5.0

**Comment by ijabz** [comment]
Thankyou for such a quick response, I have tested and can confirm fixes my notarization issue.
But one more thing, I also use an arm32 version for a custom linux machine ( https://oxygene.sk/2016/12/chromaprint-1-4-released/) and the 1.5.0 link does seem to include the arm32 build (anymore), is it possible to add an arm32 build for this new version.

**Comment by lalinsky** [comment]
I had trouble building those with the new setup, but I can give it one more try if you use them.

**Comment by ijabz** [comment]
Thanks I do still use them for this - http://www.jthink.net/songkongformelco/
