### ISSUE TITLE
 Linking error, compilation fails. 

### ISSUE THREAD

**Issue by wpope** [acoustid/chromaprint#73]
Still fails on Ubuntu 18.04   chromaprint 1.5.0
cmake  -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=ON -DCMAKE_CXX_FLAGS=-fPIC

make
[ 77%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/utils/base64.cpp.o
chromaprint-v1.5.0/src/utils/base64.cpp: In function ‘void chromaprint::Base64Encode(const string&, std::__cxx11::string&)’:
chromaprint-v1.5.0/src/utils/base64.cpp:12:13: warning: variable ‘end’ set but not used [-Wunused-but-set-variable]
  const auto end = Base64Encode(src.cbegin(), src.cend(), dest.begin());
             ^~~
chromaprint-v1.5.0/src/utils/base64.cpp: In function ‘void chromaprint::Base64Decode(const string&, std::__cxx11::string&)’:
chromaprint-v1.5.0/src/utils/base64.cpp:26:13: warning: variable ‘end’ set but not used [-Wunused-but-set-variable]
  const auto end = Base64Decode(src.cbegin(), src.cend(), dest.begin());
             ^~~
[ 81%] Building C object src/CMakeFiles/chromaprint_objs.dir/avresample/resample2.c.o
[ 81%] Built target chromaprint_objs
[ 86%] Building CXX object src/CMakeFiles/chromaprint.dir/chromaprint.cpp.o
[ 90%] Linking CXX shared library libchromaprint.so
/usr/bin/ld: /usr/lib/libavcodec.a(fft.o): relocation R_X86_64_PC32 against symbol `ff_cos_32' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/chromaprint.dir/build.make:132: recipe for target 'src/libchromaprint.so.1.5.0' failed
make[2]: *** [src/libchromaprint.so.1.5.0] Error 1
CMakeFiles/Makefile2:153: recipe for target 'src/CMakeFiles/chromaprint.dir/all' failed
make[1]: *** [src/CMakeFiles/chromaprint.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lalinsky** [comment]
As you can see from the error message, you need to compile FFmpeg with -fPIC if you want to use a static build of the FFmpeg in dynamic build of Chromaprint.
