### ISSUE TITLE
URL for "How does chromaprint work" isn't reachable anymore

### ISSUE THREAD

**Issue by PeterCodar** [acoustid/chromaprint#75]
Could you please add a PDF or similar documentation here at Github for the not reachable URL https://oxygene.sk/2011/01/how-does-chromaprint-work/

I think an explanation is still helpful.

**Comment by phw** [comment]
It's reachable (again?)

**Comment by PeterCodar** [comment]
You are right @phw
Actually, the website is available again. Since when?
