### ISSUE TITLE
Chromaprint is not compatible with ffmpeg 4

### ISSUE THREAD

**Issue by trostli** [acoustid/chromaprint#78]
Spent a long time figuring this out so wanted to post this here - Chromaprint is not yet compatible with newer versions off ffmpeg. I had to downgrade to version 2.8 and it worked for me.

**Comment by lalinsky** [comment]
What problems do you see?

The last official packages were build with FFmpeg 4.2.2, so I'm quite sure FFmpeg 4 is supported. :)
