### ISSUE TITLE
 error: 'avcodec_alloc_frame' was not declared in this scope

### ISSUE THREAD

**Issue by xiao2mo** [acoustid/chromaprint#86]
I've tried multiple versions of ffmpeg and chromaprint, could u please tell me what's wrong. oops

**Comment by Warblefly** [comment]
I'm not a chromaprint developer, but this seems to be due to FFmpeg upstream removing an API that's been deprecated for about three or four years.

https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2021-April/278670.html
