### ISSUE TITLE
Apple Silicon (arm64) support

### ISSUE THREAD

**Issue by rednoah** [acoustid/chromaprint#95]
- [x] Support for building `fpcalc` for `arm64` and publishing `x86_64+arm64` universal binaries.

@lalinsky I'd be happy to hire you to work on M1 support for chromaprint tools.

**Comment by lalinsky** [comment]
I'll try to get it done, it seems like it should be possible to cross-compile from a x86_64 mac.

**Comment by wallisch** [comment]
I made a Swift package, [ChromaSwift](https://github.com/wallisch/ChromaSwift), that runs fine on arm64 macs.
No code changes necessary, apart from some clang warnings (see https://github.com/acoustid/chromaprint/pull/88 & https://github.com/acoustid/chromaprint/pull/89)

**Comment by lalinsky** [comment]
@rednoah I don't have a M1 mac, so I can't test it myself. Fat binaries for both architectures are now built. Could you try the chromaprint-fpcalc-macos-universal artifact from https://github.com/acoustid/chromaprint/actions/runs/1610515571? If everything works as expected, I'll make a new release with these builds.

**Comment by rednoah** [comment]
Nice. I ran it on a *.mp3 file and a *.flac file and it works for both.

**Comment by lalinsky** [comment]
https://github.com/acoustid/chromaprint/releases/tag/v1.5.1
